# Generated by Django 5.1.3 on 2024-11-26 03:17

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post that is visible to all", 
        "draft": "A post that only the author can interact with",
        "archived": "An older post no longer published"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
